# File partially generated by GenAI
# Feature Selection Pipeline
# - LightGBM tuned via Optuna (objective: average precision)
# - Permutation importance on validation set
# - Two regimes: with and without OPTIME
# - Global feature set derived from union across outcomes (in NO OPTIME regime)

import argparse
import pandas as pd
import numpy as np
import lightgbm as lgb
import optuna
import matplotlib.pyplot as plt
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.inspection import permutation_importance
import warnings
import json
import logging
from src.config import SEED, BASE_PATH
from src.data_utils import get_data

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings("ignore")


def setup_logging(log_path):
    """Configure console + file logging for the feature-selection run."""
    if log_path.exists():
        log_path.unlink()
    log_path.parent.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("feat_select")
    logger.setLevel(logging.INFO)

    if logger.handlers:
        logger.handlers.clear()

    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )

    file_handler = logging.FileHandler(log_path)
    file_handler.setFormatter(formatter)

    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(formatter)

    logger.addHandler(file_handler)
    logger.addHandler(stream_handler)
    logger.propagate = False
    return logger


##Optuna objective
def create_objective(X_tr, y_tr, X_v, y_v):
    """Returns an Optuna objective function for a single outcome."""

    def objective(trial):
        params = {
            "objective": "binary",
            "verbosity": -1,
            "random_state": SEED,
            "n_estimators": trial.suggest_int("n_estimators", 100, 800, step=100),
            "max_depth": trial.suggest_int("max_depth", 3, 8),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
            "min_child_samples": trial.suggest_int(
                "min_child_samples", 10, 100, step=10
            ),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "is_unbalance": True,
        }

        model = lgb.LGBMClassifier(**params)
        model.fit(X_tr, y_tr)
        y_prob = model.predict_proba(X_v)[:, 1]
        return average_precision_score(y_v, y_prob)

    return objective


# Main workflow
def run_regime(
    X_train,
    y_train,
    X_val,
    y_val,
    outcome,
    regime_name,
    n_optuna_trials,
    n_perm_repeats,
    logger,
):
    """
    For a given feature regime, tune LightGBM per outcome,
    record validation average precision, and extract permutation importance.
    """
    logger.info("=" * 60)
    logger.info("Regime: %s | Outcome: %s", regime_name, outcome)
    logger.info("=" * 60)

    # --- Optuna tuning ---
    study = optuna.create_study(
        direction="maximize", sampler=optuna.samplers.TPESampler(seed=SEED)
    )
    study.optimize(
        create_objective(X_train, y_train, X_val, y_val),
        n_trials=n_optuna_trials,
    )

    best_params = study.best_params
    best_params["objective"] = "binary"
    best_params["verbosity"] = -1
    best_params["is_unbalance"] = True
    best_params["random_state"] = SEED
    best_ap = study.best_value

    logger.info("Best Average Precision: %.4f", best_ap)
    logger.info("Best params: %s", json.dumps(best_params))

    # --- Refit best model ---
    best_model = lgb.LGBMClassifier(**best_params)
    best_model.fit(X_train, y_train)

    # --- Permutation importance on validation set ---
    perm = permutation_importance(
        best_model,
        X_val,
        y_val,
        n_repeats=n_perm_repeats,
        scoring="average_precision",
        random_state=SEED,
    )

    feat_importance = (
        pd.DataFrame(
            {
                "feature": X_train.columns,
                "importance_mean": perm.importances_mean,
                "importance_std": perm.importances_std,
            }
        )
        .sort_values("importance_mean", ascending=False)
        .reset_index(drop=True)
    )

    results_dict = {
        "avg_precision": best_ap,
        "best_params": best_params,
        "feature_importance": feat_importance,
    }

    logger.info("Top 15 features:\n%s", feat_importance.head(15).to_string(index=False))

    return results_dict


def get_ohe_feature_groups(feature_names):
    """
    Group one-hot encoded columns by their original feature name.

    Mirrors the naming assumptions used elsewhere in the project without importing
    the heavier SHAP-based feature importance module.
    """
    groups = {}
    for feature in feature_names:
        parts = feature.split("_")
        if len(parts) == 1 or parts[0] in [
            "ETHNICITY",
            "PARTIAL GLOSSECTOMY (HEMIGLOSSECTOMY",
            "COMPOSITE",
            "LOCAL",
        ]:
            continue

        if parts[:2] == ["RACE", "NEW"]:
            group_name = "_".join(parts[:2])
        else:
            group_name = parts[0]

        groups.setdefault(group_name, []).append(feature)

    return {name: sorted(cols) for name, cols in groups.items() if len(cols) > 1}


# build feature set w/o optime
def build_global_feature_set(results, logger, min_importance=0.005):
    """
    Union of features with positive permutation importance across outcomes.
    min_importance: threshold to consider a feature as contributing signal.
    """
    selected_per_outcome = {}
    feature_names = next(iter(results.values()))["feature_importance"][
        "feature"
    ].tolist()
    ohe_groups = get_ohe_feature_groups(feature_names)
    feature_to_group = {
        feature: group_name
        for group_name, group_features in ohe_groups.items()
        for feature in group_features
    }

    for outcome, data in results.items():
        fi = data["feature_importance"]
        initially_selected = fi[fi["importance_mean"] >= min_importance][
            "feature"
        ].tolist()

        selected = set(initially_selected)
        expanded_groups = set()
        for feature in initially_selected:
            group_name = feature_to_group.get(feature)
            if group_name is None:
                continue
            selected.update(ohe_groups[group_name])
            expanded_groups.add(group_name)

        selected_per_outcome[outcome] = sorted(selected)
        if expanded_groups:
            logger.info(
                "%s: expanded one-hot groups for %s",
                outcome,
                ", ".join(sorted(expanded_groups)),
            )

    # Union across all outcomes
    global_set = sorted(set().union(*selected_per_outcome.values()))

    logger.info("=" * 60)
    logger.info("GLOBAL FEATURE SET (threshold=%s)", min_importance)
    logger.info("=" * 60)
    logger.info("Total features selected: %s", len(global_set))

    for outcome, feats in selected_per_outcome.items():
        logger.info("%s: %s features selected individually", outcome, len(feats))

    logger.info("Global set:")
    for f in global_set:
        logger.info("  - %s", f)

    return global_set, selected_per_outcome


# plot perm helper
def plot_perm_imp(results, logger, regime="WITHOUT OTPIME", top_n=20, save=True):
    """
    Plot permutation importance for each outcome.

    Params
    ------
    results: dict
        from run_regime()
    regime_name: str
        label for titles
    top_n: int
        num features to display
    save: bool
        save figs to mem
    """
    outcomes = list(results.keys())
    n_outcomes = len(outcomes)
    n_cols = min(3, n_outcomes)
    n_rows = int(np.ceil(n_outcomes / n_cols))
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(6.5 * n_cols, 4.5 * n_rows))
    axes = np.atleast_1d(axes).flatten()

    for i, outcome in enumerate(outcomes):
        ax = axes[i]
        fi = results[outcome]["feature_importance"].head(top_n).iloc[::-1]  # reverse

        ax.barh(
            fi["feature"],
            fi["importance_mean"],
            xerr=fi["importance_std"],
            color="steelblue",
            edgecolor="white",
            capsize=3,
        )

        ax.set_xlabel("Mean Avg Precision Decreaee")
        ax.set_title(f"{outcome}\n(Avg Prec={results[outcome]['avg_precision']:.4f})")
        ax.axvline(x=0, color="black", linewidth=0.8, linestyle="--")

    for j in range(n_outcomes, len(axes)):
        axes[j].set_visible(False)

    fig.suptitle(f"Permutation Importance -  {regime}", fontsize=16, fontweight="bold")
    plt.tight_layout()

    if save:
        file_path = (
            BASE_PATH / "feat_select" / f"{regime.lower().replace(" ", "_")}.pdf"
        )
        file_path.parent.mkdir(exist_ok=True, parents=True)
        fig.savefig(file_path, bbox_inches="tight")
        assert file_path.exists()
        logger.info("Saved plot to: %s", file_path)
    plt.show()


def get_final_metrics(best_params, X_train, y_train, X_val, y_val):
    model = lgb.LGBMClassifier(**best_params)
    model.fit(X_train, y_train)
    y_proba = model.predict_proba(X_val)[:, 1]
    ap = average_precision_score(y_true=y_val, y_score=y_proba)
    auroc = roc_auc_score(y_true=y_val, y_score=y_proba)
    return ap, auroc


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--outcome_list", required=True, nargs="+")
    parser.add_argument("--num_optuna_trials", type=int, required=False, default=50)
    parser.add_argument("--num_perm_repeats", type=int, required=False, default=20)
    parser.add_argument("--optime_col_name", required=False, default="OPTIME")
    args = parser.parse_args()

    optime_col = args.optime_col_name
    n_optuna_trials = args.num_optuna_trials
    n_perm_repeats = args.num_perm_repeats
    outcome_list = args.outcome_list

    results_no_optime = {}
    results_with_optime = {}
    log_path = BASE_PATH / "logs" / "feat_select.log"
    logger = setup_logging(log_path)
    logger.info("Starting feature selection for outcomes: %s", ", ".join(outcome_list))
    logger.info("Logging to: %s", log_path)

    for outcome in outcome_list:
        ## Load data
        data_dict = get_data(outcome)
        X_train = data_dict["X_train"]
        y_train = data_dict["y_train"].values.ravel()
        X_val = data_dict["X_val"]
        y_val = data_dict["y_val"].values.ravel()

        ## Run for each of w/ and w/o optime
        # --- Without OPTIME ---
        X_train_no_op = X_train.drop(columns=[optime_col])
        X_val_no_op = X_val.drop(columns=[optime_col])

        results_no_optime[outcome] = run_regime(
            X_train=X_train_no_op,
            y_train=y_train,
            X_val=X_val_no_op,
            y_val=y_val,
            outcome=outcome,
            regime_name="WITHOUT OPTIME",
            n_optuna_trials=n_optuna_trials,
            n_perm_repeats=n_perm_repeats,
            logger=logger,
        )

        # --- With OPTIME ---
        results_with_optime[outcome] = run_regime(
            X_train=X_train,
            y_train=y_train,
            X_val=X_val,
            y_val=y_val,
            outcome=outcome,
            regime_name="WITH OPTIME",
            n_optuna_trials=n_optuna_trials,
            n_perm_repeats=n_perm_repeats,
            logger=logger,
        )
    # plot permutation importance with each of w/ and w/o optime
    # plot_perm_imp(
    #     results=results_no_optime,
    #     logger=logger,
    #     regime="WITHOUT OPTIME",
    #     top_n=50,
    #     save=True,
    # )
    # plot_perm_imp(
    #     results=results_with_optime,
    #     logger=logger,
    #     regime="WITH OPTIME",
    #     top_n=50,
    #     save=True,
    # )

    ## Compare w/ optime to w/o optime
    logger.info("=" * 60)
    logger.info("REGIME COMPARISON: Average Precision")
    logger.info("=" * 60)

    comparison = pd.DataFrame(
        {
            "outcome": outcome_list,
            "AP_without_optime": [
                results_no_optime[o]["avg_precision"] for o in outcome_list
            ],
            "AP_with_optime": [
                results_with_optime[o]["avg_precision"] for o in outcome_list
            ],
        }
    )
    comparison["delta"] = comparison["AP_with_optime"] - comparison["AP_without_optime"]
    comparison["pct_change"] = (
        comparison["delta"] / comparison["AP_without_optime"] * 100
    ).round(2)

    logger.info("\n%s", comparison.to_string(index=False))

    global_features, per_outcome_features = build_global_feature_set(
        results_no_optime, logger=logger
    )

    ## validate feature set
    # Retrain on entire train set w/ selected params
    logger.info("=" * 60)
    logger.info("VALIDATION: Full vs Reduced Feature Set (without OPTIME)")
    logger.info("=" * 60)

    validation_rows = []
    for outcome in outcome_list:
        data_dict = get_data(outcome)
        X_train = data_dict["X_train"]
        y_train = data_dict["y_train"].values.ravel()
        X_val = data_dict["X_val"]
        y_val = data_dict["y_val"].values.ravel()

        X_train_no_op = X_train.drop(columns=[optime_col])
        X_val_no_op = X_val.drop(columns=[optime_col])

        prevalence = f"{y_val.mean():.2%}"

        ## FULL MODEL (including ALL vars)
        ap_full, auroc_full = get_final_metrics(
            best_params=results_with_optime[outcome]["best_params"],
            X_train=X_train,
            y_train=y_train,
            X_val=X_val,
            y_val=y_val,
        )

        #### REDUCED #####
        ## Partially (just w/o optime)
        ap_reduced, auroc_reduced = get_final_metrics(
            best_params=results_no_optime[outcome]["best_params"],
            X_train=X_train_no_op,
            y_train=y_train,
            X_val=X_val_no_op,
            y_val=y_val,
        )
        ## Fully reduced (per-outcome)
        outcome_specific_feats = per_outcome_features[outcome]
        ap_red_per_outcome, auroc_red_per_outcome = get_final_metrics(
            best_params=results_no_optime[outcome]["best_params"],
            X_train=X_train_no_op[outcome_specific_feats],
            y_train=y_train,
            X_val=X_val_no_op[outcome_specific_feats],
            y_val=y_val,
        )
        ## Fully reduced (general reduction)
        ap_red_gen, auroc_red_gen = get_final_metrics(
            best_params=results_no_optime[outcome]["best_params"],
            X_train=X_train_no_op[global_features],
            y_train=y_train,
            X_val=X_val_no_op[global_features],
            y_val=y_val,
        )
        cur_row = {
            "Outcome": outcome,
            "EventRate": prevalence,
            "AP_full": ap_full,
            "AP_reduced": ap_reduced,
            "AP_reduced_per_outcome": ap_red_per_outcome,
            "AP_reduced_generally": ap_red_gen,
            "auroc_full": auroc_full,
            "auroc_reduced": auroc_reduced,
            "auroc_reduced_per_outcome": auroc_red_per_outcome,
            "auroc_reduced_generally": auroc_red_gen,
        }
        validation_rows.append(cur_row)
    validation_df = pd.DataFrame(validation_rows)
    logger.info("\n%s", validation_df.to_string(index=False))

    logger.info("Feature selection run complete.")


if __name__ == "__main__":
    main()
