# Packages/libraries
## Logging mechanism generated by LLMs
from src.config import SEED, DEVICE
from src.nn_models import TorchNNClassifier

import joblib
import json
import warnings
import logging
import numpy as np
import optuna
import argparse
from pathlib import Path

import torch
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import roc_auc_score
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.exceptions import ConvergenceWarning
from src.data_utils import get_data


# Determinism
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def set_up_logger(log_file_path):
    """
    Create file-backed loggers for this module and for Optuna.

    Parameters
    ----------
    log_file_path : str or pathlib.Path
        Destination log file. If the file already exists, it is overwritten.

    Returns
    -------
    tuple[logging.Logger, logging.Logger, logging.FileHandler]
        The module logger, the Optuna logger, and the shared file handler.
    """
    ############ Set up paths ############
    if log_file_path.exists():
        warnings.warn(f"Over-writing log at path: {log_file_path}")
        log_file_path.unlink()
    log_file_path.parent.mkdir(exist_ok=True, parents=True)
    ############ Set up logger ############
    logger_name = f"tune.{log_file_path.resolve()}"
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.INFO)
    logger.propagate = False
    logger.handlers.clear()
    file_handler = logging.FileHandler(log_file_path, mode="a")
    file_handler.setFormatter(
        logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
    )
    logger.addHandler(file_handler)

    optuna_logger = optuna.logging.get_logger("optuna")
    optuna_logger.setLevel(logging.INFO)
    optuna_logger.propagate = False
    optuna_logger.handlers.clear()
    optuna_logger.addHandler(file_handler)
    optuna.logging.disable_default_handler()

    return logger, optuna_logger, file_handler


def log_tuning_results(logger, scoring, study):
    """
    Write a tuning summary for a completed Optuna study to the log file.

    Parameters
    ----------
    logger : logging.Logger
        Logger returned by :func:`set_up_logger`.
    scoring : str
        Scoring metric optimized during tuning.
    study : optuna.study.Study
        Completed Optuna study containing the best trial metadata.
    """
    logger.info("*" * 100)
    logger.info("Best %s: %.4f", scoring, study.best_value)
    logger.info("Params: %s", study.best_params)
    logger.info(
        "Result JSON: %s",
        json.dumps(
            {
                "scoring": scoring,
                "best_score": study.best_value,
                "best_params": study.best_params,
            },
            indent=4,
            sort_keys=True,
        ),
    )
    logger.info("*" * 100)


######################################## NEURAL NETWORK ########################################
def build_nn_estimator(trial):
    """
    Build a neural-network classifier from an Optuna trial.

    Parameters
    ----------
    trial : optuna.trial.Trial
        Trial object used to sample neural-network hyperparameters.

    Returns
    -------
    TorchNNClassifier
        Configured neural-network estimator.
    """
    n_layers = trial.suggest_int("n_layers", 2, 3)
    ### Hidden Layers ###
    hl_1 = trial.suggest_int("hl_1", 64, 384)
    hl_2 = trial.suggest_int("hl_2", 64, 384)
    h_sizes = [hl_1, hl_2]
    if n_layers == 3:
        hl_3 = trial.suggest_int("hl_3", 64, 384)
        h_sizes.append(hl_3)

    ### Dropouts ###
    dr_1 = trial.suggest_float("dr_1", 0.05, 0.6)
    dr_2 = trial.suggest_float("dr_2", 0.05, 0.6)
    dropouts = [dr_1, dr_2]
    if n_layers == 3:
        dr_3 = trial.suggest_float("dr_3", 0.05, 0.6)
        dropouts.append(dr_3)

    ####Activation ###
    act_name = trial.suggest_categorical("act_func_str", ["relu", "leaky_relu"])
    ### Epochs ###
    num_epochs = trial.suggest_int("num_epochs", 20, 120)

    ### Optimizer ####
    # opt_choice = trial.suggest_categorical("optimizer", ["adam", "adamw"])
    opt_choice = "adamw"
    lr = trial.suggest_float("lr", 3e-4, 3e-2, log=True)
    wd = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)

    ##Batch size
    bs = trial.suggest_categorical("batch_size", [64, 128, 256, 512])

    nn_clf = TorchNNClassifier(
        hidden_size_list=h_sizes,
        dropouts=dropouts,
        activation_name=act_name,
        lr=lr,
        weight_decay=wd,
        epochs=num_epochs,
        batch_size=bs,
        optimizer_str=opt_choice,
        device=DEVICE,
        seed=SEED,
    )
    return nn_clf


def make_objective_nn(X_train, y_train, scoring):
    """
    Create an Optuna objective function for neural-network tuning.

    Parameters
    ----------
    X_train : pandas.DataFrame or numpy.ndarray
        Training features used during cross-validation.
    y_train : pandas.Series or numpy.ndarray
        Training labels used during cross-validation.
    scoring : str
        Scikit-learn scoring metric passed to ``cross_val_score``.

    Returns
    -------
    callable
        Objective function that Optuna can optimize.
    """
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

    def objective(trial):
        clf = build_nn_estimator(trial)
        scores = cross_val_score(
            clf, X_train, y_train, scoring=scoring, cv=skf, n_jobs=1
        )
        return np.round(np.mean(scores), 4)

    return objective


def tune_model_nn(
    *_,
    X_train,
    y_train,
    outcome_name,
    scoring,
    log_file_path,
    n_trials,
):
    """
    Tune a neural-network model for a single outcome with Optuna.

    Parameters
    ----------
    X_train : pandas.DataFrame or numpy.ndarray
        Training features.
    y_train : pandas.Series or numpy.ndarray
        Training labels.
    outcome_name : str
        Name of the outcome being tuned.
    scoring : str
        Scikit-learn scoring metric passed to ``cross_val_score``.
    log_file_path : str or pathlib.Path
        Path to the log file written during tuning.
    n_trials : int
        Number of Optuna trials to run.

    Returns
    -------
    None

    Raises
    ------
    ValueError:
        If positional arguments are given
    """
    if _ != tuple():
        raise ValueError("This func does not take positional args")
    ## Set up logging
    logger, optuna_logger, file_handler = set_up_logger(log_file_path)

    try:
        # Create study
        study = optuna.create_study(
            study_name=f"NN_{outcome_name}_study",
            direction="maximize",
            sampler=optuna.samplers.TPESampler(seed=SEED),
            pruner=optuna.pruners.HyperbandPruner(min_resource=5, reduction_factor=3),
        )

        ############ Run optimizer ############
        study.optimize(
            make_objective_nn(X_train, y_train, scoring),
            n_trials=n_trials,
        )
        result_dict = {
            "scoring": scoring,
            "best_score": study.best_value,
            "best_params": study.best_params,
        }
        log_tuning_results(logger, scoring, study)
    finally:
        ############ Close logger ############
        logger.removeHandler(file_handler)
        optuna_logger.removeHandler(file_handler)
        file_handler.close()
    return result_dict


######################################## SVC, LGBM, LR, XGB MODELS ########################################
def lr_model_builder(trial):
    """
    Build a logistic-regression classifier from an Optuna trial.
    """
    ########## Get params ##########
    # C (regularization strength)
    C = trial.suggest_float("C", 1e-4, 1e2, log=True)
    # Regularization Penalty
    penalty = trial.suggest_categorical("penalty", ["l1", "l2", "elasticnet"])
    # Class weight (to offset imbalance)
    class_weight = trial.suggest_categorical("class_weight", ["balanced", None])
    # l1 ratio --> only useful for elasticnet (=0 means l2, =1 means l1) = None else
    if penalty == "elasticnet":
        l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)
    else:
        l1_ratio = None
    # Solver (dependent on penalty)
    # elasticnet --> ['saga]
    # l1 --> ['liblinear', 'saga']
    # l2 --> ALL
    if penalty == "elasticnet":
        solver = "saga"
    elif penalty == "l1":
        solver = trial.suggest_categorical("solver_l1", ["liblinear", "saga"])
    else:
        solver = trial.suggest_categorical(
            "solver_l2",
            ["lbfgs", "liblinear", "saga"],
        )

    intercept_scaling = 1.0

    # Need more iterations for saga/sag
    if solver in ["saga", "sag"]:
        max_iter = 10000
    else:
        max_iter = 5000
    ########## Build model ##########
    clf = LogisticRegression(
        penalty=penalty,
        C=C,
        tol=1e-4,  # default
        fit_intercept=True,  # default
        intercept_scaling=intercept_scaling,
        class_weight=class_weight,
        random_state=SEED,
        solver=solver,
        max_iter=max_iter,
        l1_ratio=l1_ratio,
        warm_start=False,
    )
    return clf


def lightgbm_model_builder(trial):
    """
    Build a LightGBM classifier from an Optuna trial.
    """
    ######### Get params ###########
    ##Core params
    learning_rate = trial.suggest_float("learning_rate", 0.005, 0.3, log=True)
    n_estimators = trial.suggest_int("n_estimators", 100, 1500)
    ##Tree shape + complexity
    max_depth = trial.suggest_categorical("max_depth", [-1, 3, 4, 5, 6, 8, 10, 12])
    if max_depth < 0:
        max_leaves = 255
    else:
        max_leaves = min(255, 2**max_depth)
    min_leaves = 12
    if min_leaves > max_leaves:
        max_leaves = min_leaves
    num_leaves = trial.suggest_int("num_leaves", min_leaves, max_leaves)

    min_data_in_leaf = trial.suggest_int("min_data_in_leaf", 5, 200)
    min_gain_to_split = trial.suggest_float("min_gain_to_split", 0.0, 0.3)

    ## Subsampling/Imbalance
    feature_fraction = trial.suggest_float("feature_fraction", 0.6, 1.0)
    bagging_fraction = trial.suggest_float("bagging_fraction", 0.6, 1.0)
    bagging_freq = trial.suggest_int("bagging_freq", 0, 20)
    scale_pos_weight = trial.suggest_float("scale_pos_weight", 1.0, 20.0, log=True)
    pos_bagging_fraction = trial.suggest_float(
        "pos_bagging_fraction", 0.8, 1.0
    )  # 1.0 samples all
    neg_bagging_fraction = trial.suggest_float(
        "neg_bagging_fraction", 0.5, 1.0
    )  # 1.0 samples all

    # Regularization
    lambda_l1 = trial.suggest_float("lambda_l1", 0.0, 25.0)
    lambda_l2 = trial.suggest_float("lambda_l2", 0.0, 25.0)

    # Binning --> More bins may improve accuracy but cost more resources
    max_bin = trial.suggest_int("max_bin", 128, 255)

    ######### Build model ###########
    clf = LGBMClassifier(
        objective="binary",
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        num_leaves=num_leaves,
        min_data_in_leaf=min_data_in_leaf,
        min_split_gain=min_gain_to_split,  # alias of min_gain_to_split in sklearn wrapper
        feature_fraction=feature_fraction,
        bagging_fraction=bagging_fraction,
        pos_bagging_fraction=pos_bagging_fraction,
        neg_bagging_fraction=neg_bagging_fraction,
        bagging_freq=bagging_freq,
        lambda_l1=lambda_l1,
        lambda_l2=lambda_l2,
        scale_pos_weight=scale_pos_weight,
        max_bin=max_bin,
        tree_learner="feature_parallel",
        n_jobs=1,
        seed=SEED,
        bagging_seed=SEED,
        feature_fraction_seed=SEED,
        deterministic=True,
        force_row_wise=True,
        verbosity=-1,
        # If you use categorical features with pandas dtypes 'category',
        # LightGBM will auto-detect them; otherwise pass categorical_feature explicitly in fit.
    )
    return clf


def svc_model_builder(trial):
    """
    Build an ``sklearn.svm.SVC`` classifier from an Optuna trial.
    """
    ######### Get params ###########
    C = trial.suggest_float("C", 1e-3, 1e3, log=True)

    kernel = trial.suggest_categorical("kernel", ["linear", "poly", "rbf"])

    # Degree only for poly kernel
    if kernel == "poly":
        degree = trial.suggest_int("degree", 2, 4)
    else:
        degree = 3  # ignored by other kernels

    # Gamma only significant for 'rbf' and 'poly'
    if kernel in ["rbf", "poly"]:
        gamma_choice = trial.suggest_categorical(
            "gamma_choice", ["scale_auto", "numerical"]
        )
        if gamma_choice == "scale_auto":
            gamma = trial.suggest_categorical("gamma_sa", ["scale", "auto"])
        else:
            gamma = trial.suggest_float("gamma_num", 1e-4, 1.0, log=True)
    else:
        gamma = "scale"

    # coef0 only significant for poly
    if kernel == "poly":
        coef0 = trial.suggest_float("coef0", 1e-3, 1.0, log=True)
    else:
        coef0 = 0.0

    shrinking = trial.suggest_categorical("shrinking", [True, False])

    # Weight given to positive class
    pos_weight = trial.suggest_float("pos_weight", 1.0, 10.0, log=True)

    ######### Build model ###########
    clf = SVC(
        C=C,
        kernel=kernel,
        degree=degree,
        gamma=gamma,
        coef0=coef0,
        shrinking=shrinking,
        probability=False,  # Outputs will be calibrated later
        class_weight={0: 1, 1: pos_weight},
        random_state=SEED,
        cache_size=1000,
    )
    return clf


# ========================> XGBOOST
def xgb_model_builder(trial):
    """
    Build an XGBoost classifier from an Optuna trial.
    """
    n_estimators = trial.suggest_int("n_estimators", 300, 1200)
    learning_rate = trial.suggest_float("learning_rate", 0.005, 0.2, log=True)
    max_depth = trial.suggest_int("max_depth", 2, 10)

    gamma = trial.suggest_float("gamma", 0.0, 10.0)
    reg_alpha = trial.suggest_float("reg_alpha", 0.0, 20.0)
    reg_lambda = trial.suggest_float("reg_lambda", 0.0, 50.0)

    subsample = trial.suggest_float("subsample", 0.5, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.5, 1.0)
    colsample_bylevel = 0.85  # keep fixed in stage 1

    scale_pos_weight = trial.suggest_float("scale_pos_weight", 1.0, 15.0, log=True)

    min_child_weight = trial.suggest_int("min_child_weight", 1, 30)

    return XGBClassifier(
        objective="binary:logistic",  # no focal loss for stage 1
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        gamma=gamma,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        colsample_bylevel=colsample_bylevel,
        scale_pos_weight=scale_pos_weight,
        min_child_weight=min_child_weight,
        tree_method="hist",
        n_jobs=1,
        random_state=SEED,
        eval_metric="map",  # mean avg precision
    )


def make_objective(X_train, y_train, model_builder, scoring="average_precision"):
    """
    Create an Optuna objective function for non-neural-network models.

    Parameters
    ----------
    X_train : pandas.DataFrame or numpy.ndarray
        Training features used during cross-validation.
    y_train : pandas.Series or numpy.ndarray
        Training labels used during cross-validation.
    model_builder : callable
        Function that accepts an Optuna trial and returns an estimator.
    scoring : str, default="average_precision"
        Scikit-learn scoring metric passed to ``cross_val_score``.

    Returns
    -------
    callable
        Objective function that Optuna can optimize.
    """
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

    def objective(trial):
        model = model_builder(trial)
        scores = cross_val_score(
            model, X_train, y_train, scoring=scoring, cv=skf, n_jobs=1
        )
        return np.round(np.mean(scores), 4)

    return objective


def tune_single_model_outcome(
    *_,
    model_builder,
    model_abrv,
    outcome_name,
    X_train,
    y_train,
    scoring,
    log_file_path,
    n_trials=500,
):
    """
    Tune one non-neural-network model for a single outcome with Optuna.

    Parameters
    ----------
    model_builder : callable
        Function that accepts an Optuna trial and returns an estimator.
    model_abrv : str
        Short model name used in logging, such as ``lr``, ``svc``, ``lgbm``, or ``xgb``.
    outcome_name : str
        Name of the outcome being tuned.
    X_train : pandas.DataFrame or numpy.ndarray
        Training features.
    y_train : pandas.Series or numpy.ndarray
        Training labels.
    scoring : str
        Scikit-learn scoring metric passed to ``cross_val_score``.
    log_file_path : str or pathlib.Path
        Path to the log file written during tuning.
    n_trials : int, default=500
        Number of Optuna trials to run.

    Returns
    -------
    dict
        Dictionary with the scoring metric, best score, and best hyperparameters.

    Raises
    ------
    ValueError:
        If positional arguments are given
    """
    if _ != tuple():
        raise ValueError("This func does not take positional args")
    ## Set Up logger
    logger, optuna_logger, file_handler = set_up_logger(log_file_path)
    try:
        ############ Run for single outcome ############
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=ConvergenceWarning)
            study = optuna.create_study(
                study_name=f"{model_abrv}_{outcome_name}_study",
                direction="maximize",
                sampler=optuna.samplers.TPESampler(seed=SEED),
                pruner=optuna.pruners.HyperbandPruner(),
            )
            study.optimize(
                make_objective(X_train, y_train, model_builder, scoring),  # type: ignore
                n_trials=n_trials,
            )
            result_dict = {
                "scoring": scoring,
                "best_score": study.best_value,
                "best_params": study.best_params,
            }
        log_tuning_results(logger, scoring, study)
    finally:
        ############ Close logger ############
        logger.removeHandler(file_handler)
        optuna_logger.removeHandler(file_handler)
        file_handler.close()
    return result_dict


######################################## FOR ALL MODELS ########################################
def get_prelim_results(
    *_,
    results_dict,
    model_builder,
    model_abrv,
    outcome_dict,
    model_save_dir=None,
):
    """
    Fit tuned models, print train/validation AUROC values, and optionally save them.

    Parameters
    ----------
    results_dict : dict
        Mapping from outcome names to tuning results.
        Format:
        {
            outcome_type (str): {
                'best_score': float,
                'best_params': dict
            }
        }
    model_builder : callable
        Function that accepts an Optuna trial and returns an estimator.

    model_abrv : str
        Abbreviation of the model being evaluated.
    outcome_dict : dict
        Mapping from outcome names to train/validation/test splits.
        Format:
        {
            outcome_type (str): {
                'X_train': pandas dataframe,
                'y_train': pandas dataframe
                'X_val': pandas dataframe,
                'y_val': pandas dataframe
                'X_test': pandas dataframe,
                'y_test': pandas dataframe
            }
        }
    model_save_dir : pathlib.Path or None, default=None
        Directory where fitted models are saved. If ``None``, models are not saved.

    Returns
    -------
    None

    Raises
    ------
    ValueError:
        If positional arguments are given
    """
    if _ != tuple():
        raise ValueError("This function does not take position arguments!")

    print(f"{'-'*30} {model_abrv} {'-'*30}")
    for outcome, results in results_dict.items():
        ##Get tuning results
        best_score = results["best_score"]
        best_params = results["best_params"]

        trial = optuna.trial.FixedTrial(best_params)
        model = model_builder(trial)

        ##### Train model #####
        X_train = outcome_dict[outcome]["X_train"]
        y_train = outcome_dict[outcome]["y_train"]
        model.fit(X_train, y_train.values.ravel())

        ##### Export model #####
        if model_save_dir:
            # n_layers only provided if using NN
            if model_abrv == "nn":
                save_path = model_save_dir / f"nn.pt"
                if save_path.exists():
                    save_path.unlink()
                save_path.parent.mkdir(exist_ok=True, parents=True)
                torch.save(
                    {
                        "h_params": best_params,
                        "state_dict": model.model_.state_dict(),
                        "feature_names_in_": getattr(model, "feature_names_in_"),
                    },  # type: ignore
                    save_path,
                )
            # for all other models (lr, svc, lgbm)
            else:
                save_path = model_save_dir / outcome / f"{model_abrv}.joblib"
                if save_path.exists():
                    save_path.unlink()
                save_path.parent.mkdir(exist_ok=True, parents=True)
                joblib.dump(model, save_path)

        ##### Get prelim results #####
        X_val = outcome_dict[outcome]["X_val"]
        y_val = outcome_dict[outcome]["y_val"]

        ## Neural Network (model_abrv can be nn-2 or nn-3)
        if model_abrv == "nn":
            # nn class auto-implements AUROC for .score()
            train_auc = model.score(X_train, y_train)
            val_auc = model.score(X_val, y_val)
        else:
            ## SVC
            if model_abrv == "svc":
                # not probabilities, but appropriately ranked
                x_train_output = model.decision_function(X_train)  # type: ignore
                x_val_output = model.decision_function(X_val)  # type: ignore
            ## All other models (lr, lgbm)
            else:
                # probability of class 1
                x_train_output = model.predict_proba(X_train)[:, 1]
                x_val_output = model.predict_proba(X_val)[:, 1]
            ## Only compute these separately for non-NN models
            train_auc = roc_auc_score(y_train, x_train_output)
            val_auc = roc_auc_score(y_val, x_val_output)

        ##### Output results #####
        print(f"Outcome: \t{outcome}")
        print(f"Best CV AUROC: \t{best_score:.3f}")
        print(f"Train AUROC: \t{train_auc:.3f}")
        print(f"Val ROC AUC: \t{val_auc:.3f}")
        print(f"PARAMS: \t{best_params}")
        print("*" * 10)


def main():
    MODEL_BUILDER_DICT = {
        "lr": lr_model_builder,
        "lgbm": lightgbm_model_builder,
        "svc": svc_model_builder,
        "xgb": xgb_model_builder,
    }

    parser = argparse.ArgumentParser()
    parser.add_argument("--model_abrv", required=True)
    parser.add_argument("--outcome_name", required=True)
    parser.add_argument("--scoring", required=True)
    parser.add_argument("--log_file_path", required=True)
    parser.add_argument("--import_dir", required=True)
    parser.add_argument("--n_trials", required=False, type=int, default=500)
    args = parser.parse_args()

    ## Get train data
    outcome_name = args.outcome_name
    import_dir = args.import_dir
    import_dir = Path(import_dir)
    outcome_data = get_data(outcome_folder=outcome_name, file_dir=import_dir)
    X_train = outcome_data["X_train"]
    y_train = outcome_data["y_train"].values.ravel()

    ## Call tuners
    model_abrv = args.model_abrv
    log_path = Path(args.log_file_path)
    if model_abrv == "nn":
        result_dict = tune_model_nn(
            X_train=X_train,
            y_train=y_train,
            outcome_name=outcome_name,
            scoring=args.scoring,
            log_file_path=log_path,
            n_trials=args.n_trials,
        )
    else:
        result_dict = tune_single_model_outcome(
            model_builder=MODEL_BUILDER_DICT[model_abrv],
            model_abrv=model_abrv,
            outcome_name=outcome_name,
            X_train=X_train,
            y_train=y_train,
            scoring=args.scoring,
            log_file_path=log_path,
            n_trials=args.n_trials,
        )
    result_path = Path(log_path).with_suffix(".json")
    with open(result_path, "w") as f:
        json.dump(result_dict, f, indent=4)


if __name__ == "__main__":
    main()
