# Packages/libraries
## Logging mechanism generated by LLMs
from src.config import SEED, DEVICE
from src.nn_models import TorchNNClassifier

import joblib
import json
import warnings
import logging
import numpy as np
import optuna
import argparse
from pathlib import Path

import torch
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.exceptions import ConvergenceWarning
from src.data_utils import get_data
from sklearn.metrics import roc_auc_score, average_precision_score

# Determinism
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def set_up_logger(log_file_path):
    """
    Create console-backed loggers for this module and for Optuna.

    Parameters
    ----------
    log_file_path : str or pathlib.Path
        Log path used only to derive a stable logger name.

    Returns
    -------
    tuple[logging.Logger, logging.Logger, logging.StreamHandler]
        The module logger, the Optuna logger, and the shared stream handler.
    """
    ############ Set up logger ############
    logger_name = f"tune.{log_file_path.resolve()}"
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.INFO)
    logger.propagate = False
    logger.handlers.clear()
    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(
        logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
    )
    logger.addHandler(stream_handler)

    optuna_logger = optuna.logging.get_logger("optuna")
    optuna_logger.setLevel(logging.INFO)
    optuna_logger.propagate = False
    optuna_logger.handlers.clear()
    optuna_logger.addHandler(stream_handler)
    optuna.logging.disable_default_handler()

    return logger, optuna_logger, stream_handler


def log_tuning_results(logger, scoring, study):
    """
    Write a tuning summary for a completed Optuna study to the log file.

    Parameters
    ----------
    logger : logging.Logger
        Logger returned by :func:`set_up_logger`.
    scoring : str
        Scoring metric optimized during tuning.
    study : optuna.study.Study
        Completed Optuna study containing the best trial metadata.
    """
    logger.info("*" * 100)
    logger.info("Best %s: %.4f", scoring, study.best_value)
    logger.info("Params: %s", study.best_params)
    logger.info(
        "Result JSON: %s",
        json.dumps(
            {
                "scoring": scoring,
                "best_score": study.best_value,
                "best_params": study.best_params,
            },
            indent=4,
            sort_keys=True,
        ),
    )
    logger.info("*" * 100)


def make_objective(
    X_train, y_train, model_builder, scoring="average_precision", cv_jobs=1
):
    """
    Create an Optuna objective function for non-neural-network models.

    Parameters
    ----------
    X_train : pandas.DataFrame or numpy.ndarray
        Training features used during cross-validation.
    y_train : pandas.Series or numpy.ndarray
        Training labels used during cross-validation.
    model_builder : callable
        Function that accepts an Optuna trial and returns an estimator.
    scoring : str, default="average_precision"
        Scikit-learn scoring metric passed to ``cross_val_score``.

    Returns
    -------
    callable
        Objective function that Optuna can optimize.
    """

    def objective(trial):
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
        model = model_builder(trial)
        scores = cross_val_score(
            model,
            X_train,
            y_train,
            scoring=scoring,
            cv=skf,
            n_jobs=cv_jobs,
        )
        return float(np.mean(scores))

    return objective


######################################## MODEL BUILDERS ########################################
def lr_model_builder(trial):
    """
    Build a logistic-regression classifier from an Optuna trial.
    """
    ########## Get params ##########
    # C (regularization strength)
    C = trial.suggest_float("C", 1e-4, 1e2, log=True)
    # Regularization Penalty
    penalty = trial.suggest_categorical("penalty", ["l1", "l2", "elasticnet"])
    # Class weight (to offset imbalance)
    class_weight = trial.suggest_categorical("class_weight", ["balanced", None])
    # l1 ratio --> only useful for elasticnet (=0 means l2, =1 means l1) = None else
    if penalty == "elasticnet":
        l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)
    else:
        l1_ratio = None
    # Solver (dependent on penalty)
    # elasticnet --> ['saga]
    # l1 --> ['liblinear', 'saga']
    # l2 --> ALL
    if penalty == "elasticnet":
        solver = "saga"
    elif penalty == "l1":
        solver = trial.suggest_categorical("solver_l1", ["liblinear", "saga"])
    else:
        solver = trial.suggest_categorical(
            "solver_l2",
            ["lbfgs", "liblinear", "saga"],
        )

    intercept_scaling = 1.0

    # Need more iterations for saga/sag
    if solver in ["saga", "sag"]:
        max_iter = 10000
    else:
        max_iter = 5000
    ########## Build model ##########
    clf = LogisticRegression(
        penalty=penalty,
        C=C,
        tol=1e-4,  # default
        fit_intercept=True,  # default
        intercept_scaling=intercept_scaling,
        class_weight=class_weight,
        random_state=SEED,
        solver=solver,
        max_iter=max_iter,
        l1_ratio=l1_ratio,
        warm_start=False,
    )
    return clf


def lightgbm_model_builder(trial):
    """
    Build a LightGBM classifier from an Optuna trial.
    """
    ######### Get params ###########
    ##Core params
    learning_rate = trial.suggest_float("learning_rate", 1e-3, 0.3, log=True)
    n_estimators = trial.suggest_int("n_estimators", 100, 1500)
    ##Tree shape + complexity
    max_depth = trial.suggest_categorical("max_depth", [-1, 2, 3, 4, 5, 6, 8, 10, 12])
    if max_depth < 0:
        max_leaves = 255
    else:
        max_leaves = min(255, 2**max_depth)
    min_leaves = 6
    if min_leaves > max_leaves:
        max_leaves = min_leaves
    num_leaves = trial.suggest_int("num_leaves", min_leaves, max_leaves)

    min_data_in_leaf = trial.suggest_int("min_data_in_leaf", 5, 200)
    min_gain_to_split = trial.suggest_float("min_gain_to_split", 0.0, 0.3)

    ## Subsampling/Imbalance
    feature_fraction = trial.suggest_float("feature_fraction", 0.6, 1.0)
    bagging_fraction = trial.suggest_float("bagging_fraction", 0.6, 1.0)
    bagging_freq = trial.suggest_int("bagging_freq", 0, 20)
    scale_pos_weight = trial.suggest_float("scale_pos_weight", 1.0, 20.0, log=True)
    pos_bagging_fraction = trial.suggest_float(
        "pos_bagging_fraction", 0.8, 1.0
    )  # 1.0 samples all
    neg_bagging_fraction = trial.suggest_float(
        "neg_bagging_fraction", 0.5, 1.0
    )  # 1.0 samples all

    # Regularization
    lambda_l1 = trial.suggest_float("lambda_l1", 1e-5, 25.0, log=True)
    lambda_l2 = trial.suggest_float("lambda_l2", 1e-5, 25.0, log=True)

    # Binning --> More bins may improve accuracy but cost more resources
    max_bin = trial.suggest_int("max_bin", 128, 255)

    ######### Build model ###########
    clf = LGBMClassifier(
        objective="binary",
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        num_leaves=num_leaves,
        min_data_in_leaf=min_data_in_leaf,
        min_split_gain=min_gain_to_split,  # alias of min_gain_to_split in sklearn wrapper
        feature_fraction=feature_fraction,
        bagging_fraction=bagging_fraction,
        pos_bagging_fraction=pos_bagging_fraction,
        neg_bagging_fraction=neg_bagging_fraction,
        bagging_freq=bagging_freq,
        lambda_l1=lambda_l1,
        lambda_l2=lambda_l2,
        scale_pos_weight=scale_pos_weight,
        max_bin=max_bin,
        tree_learner="feature_parallel",
        n_jobs=1,
        seed=SEED,
        bagging_seed=SEED,
        feature_fraction_seed=SEED,
        deterministic=True,
        force_row_wise=True,
        verbosity=-1,
        # If you use categorical features with pandas dtypes 'category',
        # LightGBM will auto-detect them; otherwise pass categorical_feature explicitly in fit.
    )
    return clf


def svc_model_builder(trial, probability=False):
    """
    Build an ``sklearn.svm.SVC`` classifier from an Optuna trial.
    """
    ######### Get params ###########
    C = trial.suggest_float("C", 1e-3, 50, log=True)

    kernel = trial.suggest_categorical("kernel", ["linear", "poly", "rbf"])

    # Degree only for poly kernel
    if kernel == "poly":
        degree = trial.suggest_int("degree", 2, 4)
    else:
        degree = 3  # ignored by other kernels

    # Gamma only significant for 'rbf' and 'poly'
    if kernel in ["rbf", "poly"]:
        gamma_choice = trial.suggest_categorical(
            "gamma_choice", ["scale_auto", "numerical"]
        )
        if gamma_choice == "scale_auto":
            gamma = trial.suggest_categorical("gamma_sa", ["scale", "auto"])
        else:
            gamma = trial.suggest_float("gamma_num", 1e-4, 1.0, log=True)
    else:
        gamma = "scale"

    # coef0 only significant for poly
    if kernel == "poly":
        coef0 = trial.suggest_float("coef0", 1e-3, 1.0, log=True)
    else:
        coef0 = 0.0

    shrinking = trial.suggest_categorical("shrinking", [True, False])

    # Weight given to positive class
    pos_weight = trial.suggest_float("pos_weight", 1.0, 10.0, log=True)

    ######### Build model ###########
    clf = SVC(
        C=C,
        kernel=kernel,
        degree=degree,
        gamma=gamma,
        coef0=coef0,
        shrinking=shrinking,
        probability=probability,  # False on tuning, can always set True or calibrate later
        class_weight={0: 1, 1: pos_weight},
        random_state=SEED,
        cache_size=1000,
    )
    return clf


def xgb_model_builder(trial):
    """
    Build an XGBoost classifier from an Optuna trial.
    """
    n_estimators = trial.suggest_int("n_estimators", 300, 1200)
    learning_rate = trial.suggest_float("learning_rate", 0.005, 0.2, log=True)
    max_depth = trial.suggest_int("max_depth", 2, 10)

    gamma = trial.suggest_float("gamma", 0.0, 10.0)
    reg_alpha = trial.suggest_float("reg_alpha", 1e-5, 20.0, log=True)
    reg_lambda = trial.suggest_float("reg_lambda", 1e-5, 25.0, log=True)

    subsample = trial.suggest_float("subsample", 0.5, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.5, 1.0)
    colsample_bylevel = 0.85  # keep fixed in stage 1

    scale_pos_weight = trial.suggest_float("scale_pos_weight", 1.0, 15.0, log=True)

    min_child_weight = trial.suggest_int("min_child_weight", 1, 30)

    return XGBClassifier(
        objective="binary:logistic",  # no focal loss for stage 1
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        gamma=gamma,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        colsample_bylevel=colsample_bylevel,
        scale_pos_weight=scale_pos_weight,
        min_child_weight=min_child_weight,
        tree_method="hist",
        n_jobs=1,
        random_state=SEED,
        eval_metric="map",  # mean avg precision
    )


def nn_model_builder(trial):
    """
    Build a neural-network classifier from an Optuna trial.

    Parameters
    ----------
    trial : optuna.trial.Trial
        Trial object used to sample neural-network hyperparameters.

    Returns
    -------
    TorchNNClassifier
        Configured neural-network estimator.
    """
    n_layers = trial.suggest_int("n_layers", 2, 3)
    ### Hidden Layers ###
    hl_1 = trial.suggest_int("hl_1", 32, 384)
    hl_2 = trial.suggest_int("hl_2", 32, 384)
    h_sizes = [hl_1, hl_2]
    if n_layers == 3:
        hl_3 = trial.suggest_int("hl_3", 32, 384)
        h_sizes.append(hl_3)

    ### Dropouts ###
    dr_1 = trial.suggest_float("dr_1", 0.05, 0.6)
    dr_2 = trial.suggest_float("dr_2", 0.05, 0.6)
    dropouts = [dr_1, dr_2]
    if n_layers == 3:
        dr_3 = trial.suggest_float("dr_3", 0.05, 0.6)
        dropouts.append(dr_3)

    ####Activation ###
    act_name = trial.suggest_categorical("act_func_str", ["relu", "leaky_relu"])
    if act_name == "leaky_relu":
        neg_slope = trial.suggest_float("neg_slope", 1e-3, 1e-1, log=True)
    else:
        neg_slope = 0.01  # unused
    ### Epochs ###
    num_epochs = trial.suggest_int("num_epochs", 20, 300)

    ### Optimizer ####
    # opt_choice = trial.suggest_categorical("optimizer", ["adam", "adamw"])
    opt_choice = "adamw"
    lr = trial.suggest_float("lr", 3e-4, 3e-2, log=True)
    wd = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)

    ##Batch size
    bs = trial.suggest_categorical("batch_size", [64, 128, 256, 512])

    nn_clf = TorchNNClassifier(
        hidden_size_list=h_sizes,
        dropouts=dropouts,
        activation_name=act_name,
        lr=lr,
        weight_decay=wd,
        epochs=num_epochs,
        batch_size=bs,
        optimizer_str=opt_choice,
        device=DEVICE,
        seed=SEED,
        neg_slope=neg_slope,
    )
    return nn_clf


######################################## FOR ALL MODELS ########################################
def tune_single_model_outcome(
    *_,
    model_builder,
    model_abrv,
    outcome_name,
    X_train,
    y_train,
    scoring,
    log_file_path,
    cv_jobs,
    n_trials=500,
):
    """
    Tune one non-neural-network model for a single outcome with Optuna.

    Parameters
    ----------
    model_builder : callable
        Function that accepts an Optuna trial and returns an estimator.
    model_abrv : str
        Short model name used in logging, such as ``lr``, ``svc``, ``lgbm``, or ``xgb``.
    outcome_name : str
        Name of the outcome being tuned.
    X_train : pandas.DataFrame or numpy.ndarray
        Training features.
    y_train : pandas.Series or numpy.ndarray
        Training labels.
    scoring : str
        Scikit-learn scoring metric passed to ``cross_val_score``.
    log_file_path : str or pathlib.Path
        Path to the log file written during tuning.
    n_trials : int, default=500
        Number of Optuna trials to run.
    cv_jobs: str
        Number of parallel cross-val jobs
    Returns
    -------
    dict
        Dictionary with the scoring metric, best score, and best hyperparameters.

    Raises
    ------
    ValueError:
        If positional arguments are given
    """
    if _ != tuple():
        raise ValueError("This func does not take positional args")
    ## Set Up logger
    logger, optuna_logger, stream_handler = set_up_logger(log_file_path)
    try:
        ############ Run for single outcome ############
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=ConvergenceWarning)
            study = optuna.create_study(
                study_name=f"{model_abrv}_{outcome_name}_study",
                direction="maximize",
                sampler=optuna.samplers.TPESampler(seed=SEED),
                pruner=optuna.pruners.NopPruner(),  # objective func returns no intermediate values
            )
            study.optimize(
                make_objective(X_train, y_train, model_builder, scoring, cv_jobs),  # type: ignore
                n_trials=n_trials,
            )
            result_dict = {
                "scoring": scoring,
                "best_score": study.best_value,
                "best_params": study.best_params,
            }
        log_tuning_results(logger, scoring, study)
    finally:
        ############ Close logger ############
        logger.removeHandler(stream_handler)
        optuna_logger.removeHandler(stream_handler)
        stream_handler.close()
    return result_dict


def get_prelim_results(
    *_,
    best_params,
    outcome_data,
    model_builder,
    model_abrv,
    model_save_dir=None,
):
    """
    Fit tuned models, print train/validation AUROC values, and optionally save them.

    Parameters
    ----------
    best_params : dict
        Mapping from param string to param values from tuning stage
    outcome_data : dict
        Mapping from outcome names to train/validation/test splits.
        Format:
        {
            outcome_type (str): {
                'X_train': pandas dataframe,
                'y_train': pandas dataframe
                'X_val': pandas dataframe,
                'y_val': pandas dataframe
                'X_test': pandas dataframe,
                'y_test': pandas dataframe
            }
        }
    model_builder : callable
        Function that accepts an Optuna trial and returns an estimator.

    model_abrv : str
        Abbreviation of the model being evaluated.

    model_save_dir : pathlib.Path or None, default=None
        Directory where fitted models are saved. If `None`, models are not saved.

    Returns
    -------
    None

    Raises
    ------
    ValueError:
        If positional arguments are given
    """
    if _ != tuple():
        raise ValueError("This function does not take position arguments!")

    trial = optuna.trial.FixedTrial(best_params)
    model = model_builder(trial)
    ##### Train model #####
    X_train = outcome_data["X_train"]
    y_train = outcome_data["y_train"].values.ravel()
    model.fit(X_train, y_train)

    ##### Export model #####
    if model_save_dir:
        # n_layers only provided if using NN
        if model_abrv == "nn":
            save_path = model_save_dir / f"nn.pt"
            if save_path.exists():
                save_path.unlink()
            save_path.parent.mkdir(exist_ok=True, parents=True)
            torch.save(
                {
                    "h_params": best_params,
                    "state_dict": model.model_.state_dict(),
                    "feature_names_in_": getattr(model, "feature_names_in_"),
                },  # type: ignore
                save_path,
            )
        # for all other models (lr, svc, lgbm)
        else:
            save_path = model_save_dir / f"{model_abrv}.joblib"
            if save_path.exists():
                save_path.unlink()
            save_path.parent.mkdir(exist_ok=True, parents=True)
            joblib.dump(model, save_path)

    ##### Get prelim results #####
    X_val = outcome_data["X_val"]
    y_val = outcome_data["y_val"].values.ravel()
    # probability of class 1
    if model_abrv == "svc":
        y_proba_train = model.decision_function(X_train)
        y_proba_val = model.decision_function(X_val)
    else:
        y_proba_train = model.predict_proba(X_train)[:, 1]
        y_proba_val = model.predict_proba(X_val)[:, 1]
    ## Get metrics
    train_auc = roc_auc_score(y_train, y_proba_train)
    val_auc = roc_auc_score(y_val, y_proba_val)
    train_ap = average_precision_score(y_train, y_proba_train)
    val_ap = average_precision_score(y_val, y_proba_val)

    return {
        "prelim_train_auc": train_auc,
        "prelim_val_auc": val_auc,
        "prelim_train_ap": train_ap,
        "prelim_val_ap": val_ap,
    }


def main():
    MODEL_BUILDER_DICT = {
        "lr": lr_model_builder,
        "lgbm": lightgbm_model_builder,
        "svc": svc_model_builder,
        "xgb": xgb_model_builder,
        "nn": nn_model_builder,
    }

    parser = argparse.ArgumentParser()
    parser.add_argument("--model_abrv", required=True)
    parser.add_argument("--outcome_name", required=True)
    parser.add_argument("--scoring", required=True)
    parser.add_argument("--log_file_path", required=True)
    parser.add_argument("--import_dir", required=True)
    parser.add_argument("--model_save_dir", required=False, default="None")
    parser.add_argument("--n_trials", required=False, type=int, default=500)
    parser.add_argument("--cv_jobs", required=False, type=int, default=1)
    args = parser.parse_args()

    ## Get train data
    outcome_name = args.outcome_name
    import_dir = args.import_dir
    import_dir = Path(import_dir)
    outcome_data = get_data(outcome_folder=outcome_name, file_dir=import_dir)
    X_train = outcome_data["X_train"]
    y_train = outcome_data["y_train"].values.ravel()

    ## Call tuners
    model_abrv = args.model_abrv
    log_path = Path(args.log_file_path)
    if log_path.exists():
        log_path.unlink()
    log_path.parent.mkdir(exist_ok=True, parents=True)
    tune_dict = tune_single_model_outcome(
        model_builder=MODEL_BUILDER_DICT[model_abrv],
        model_abrv=model_abrv,
        outcome_name=outcome_name,
        X_train=X_train,
        y_train=y_train,
        scoring=args.scoring,
        log_file_path=log_path,
        n_trials=args.n_trials,
        cv_jobs=args.cv_jobs,
    )
    result_path = log_path.with_suffix(".json")

    ## Get results on val set
    if args.model_save_dir == "None":
        model_save_dir = None
    else:
        model_save_dir = Path(args.model_save_dir)
    prelim_results_dict = get_prelim_results(
        best_params=tune_dict["best_params"],
        outcome_data=outcome_data,
        model_builder=MODEL_BUILDER_DICT[model_abrv],
        model_abrv=model_abrv,
        model_save_dir=model_save_dir,
    )
    result_dict = {**tune_dict, **prelim_results_dict}
    with open(result_path, "w") as f:
        json.dump(result_dict, f, indent=4)


if __name__ == "__main__":
    main()
